"""Prompts e schemas JSON estritos para grupos de apólices/boleto e extração."""
EVIDENCE={"type":"object","additionalProperties":False,"properties":{"valor":{"type":["string","number","null"]},"fonte":{"type":"string","enum":["APOLICE","BOLETO","AMBOS","NAO_IDENTIFICADO"]},"confianca":{"type":"number","minimum":0,"maximum":1}},"required":["valor","fonte","confianca"]}
CNPJ_EVIDENCE={**EVIDENCE,"properties":{**EVIDENCE["properties"],"valor":{"type":["string","null"]}}}
FIELD_NAMES=["empresa","empresa_normalizada","cnpj","orgao","numero_concorrencia_original","numero_concorrencia_normalizado","processo_sei","lote","objeto","vigencia_data_inicial","vigencia_data_final","valor_premio","numero_registro_susep","linha_digitavel_boleto"]
POLICY_SCHEMA={"type":"object","additionalProperties":False,"properties":{**{name:(CNPJ_EVIDENCE if name=="cnpj" else EVIDENCE) for name in FIELD_NAMES},"par_coerente":{"type":"boolean"},"orgao_normalizado":{"type":["string","null"]},"tipo_empresa":{"type":["string","null"],"enum":["THI","PHAS",None]},"nome_pasta":{"type":["string","null"]},"nome_apolice":{"type":["string","null"]},"nome_boleto":{"type":["string","null"]},"confianca_geral":{"type":"number","minimum":0,"maximum":1},"campos_com_duvida":{"type":"array","items":{"type":"string"}},"observacoes":{"type":["string","null"]}},"required":FIELD_NAMES+["par_coerente","orgao_normalizado","tipo_empresa","nome_pasta","nome_apolice","nome_boleto","confianca_geral","campos_com_duvida","observacoes"]}
GROUP_SCHEMA={"type":"object","additionalProperties":False,"properties":{"lote":EVIDENCE,"apolice":{"type":["string","null"]},"boleto":{"type":["string","null"]}},"required":["lote","apolice","boleto"]}
ROLE_SCHEMA={"type":"object","additionalProperties":False,"properties":{"grupos":{"type":"array","items":GROUP_SCHEMA},"outros":{"type":"array","items":{"type":"string"}},"observacoes":{"type":["string","null"]}},"required":["grupos","outros","observacoes"]}
SYSTEM_PROMPT="""Você é um sistema multimodal de extração documental de apólices de seguro relacionadas a licitações brasileiras. Nesta chamada recebe as primeiras páginas de UMA apólice e o boleto completo associado ao mesmo grupo/lote. Extraia somente informações efetivamente sustentadas pelos documentos. Defina par_coerente=true somente se a apólice e o boleto se referirem ao mesmo contrato/licitação e ao mesmo lote quando houver lotes identificáveis; se houver conflito ou não for seguro, false. Compare órgão, número da concorrência e identificadores explícitos de lote nos dois arquivos; registre conflitos em observacoes/campos_com_duvida. Uma associação classificada anteriormente não deve ser aceita sem essa verificação independente.

NUNCA invente, complete dígitos, deduza dados ausentes ou transforme incerteza em certeza. Para dado ausente/ilegível retorne valor=null, fonte=NAO_IDENTIFICADO, confiança baixa e inclua o campo em campos_com_duvida. A confiança é por campo e baseada na evidência legível. Indique APOLICE, BOLETO, AMBOS ou NAO_IDENTIFICADO.

Prioridade: seguro, empresa, CNPJ da empresa/tomador, órgão, concorrência, SEI, lote, objeto, vigência e SUSEP: apólice; linha digitável: boleto; prêmio: apólice, mencionando conflito com boleto. Preserve o nome jurídico original em empresa e transcreva o CNPJ apenas quando legível no documento. Empresa normalizada somente THI ou PHAS quando sustentada pelos documentos. Datas ISO YYYY-MM-DD; prêmio número decimal. Linha digitável transcrita exatamente, sem validação/correção/completar. Preserve número original da concorrência e produza forma normalizada substituindo separadores por hífens, sem alterar algarismos. lote deve ser o identificador literal verificável; se não estiver explícito ou legível, null (não deduza pelo nome do arquivo).

Nomes finais serão gerados pelo Python, não use sugestões da IA como caminhos."""
def role_prompt(names:list[str])->str:
    return ("Classifique semanticamente TODOS os PDFs anexados. Pode haver muitas apólices e boletos, documentos de múltiplos lotes e documentos OUTRO. Devolva exatamente cada nome de arquivo anexado uma vez, sem alterar grafia. Agrupe pares pela correspondência semântica entre conteúdo dos PDFs, identificadores do lote (que podem estar no nome, no corpo, em tabelas, boleto ou apólice), órgão e concorrência. NUNCA associe apenas pela ordem dos anexos. Não associe documentos de lotes diferentes. Para cada grupo, retorne lote como objeto {valor, fonte, confianca}; use valor null se não conseguir identificar e fonte NAO_IDENTIFICADO. Retorne apolice e boleto como nomes exatos, null se a contraparte faltar/for ambígua. Arquivos alheios vão em outros. Não descarte documentos nem invente lotes. Se houver ambiguidade, descreva em observacoes e deixe o grupo incompleto para revisão. Os nomes anexados são: "+"; ".join(names))
def policy_prompt(company_names:list[str]|None=None,expected_lot:str|None=None)->str:
    references=""
    if company_names:references="\nNomes jurídicos de referência configurados: "+"; ".join(company_names)+". Servem apenas para reconhecer nomes impressos, não como prova independente."
    group=""
    if expected_lot is not None:group=f"\nA classificação anterior associou este par ao lote {expected_lot!r}. Confira o lote nos documentos; se não houver evidência documental, lote deve ser null. Não copie cegamente o identificador de contexto."
    return SYSTEM_PROMPT+references+group+"\nRetorne exclusivamente JSON compatível com schema strict. Cada campo em FIELD_NAMES é {valor, fonte, confianca}. Para lote, inclua evidência/confiança; se não identificável, null com baixa confiança."
