"""Prompts e schemas JSON estritos para grupos de apólices/boleto e extração."""
EVIDENCE={"type":"object","additionalProperties":False,"properties":{"valor":{"type":["string","number","null"]},"fonte":{"type":"string","enum":["APOLICE","BOLETO","AMBOS","NAO_IDENTIFICADO"]},"confianca":{"type":"number","minimum":0,"maximum":1}},"required":["valor","fonte","confianca"]}
CNPJ_EVIDENCE={**EVIDENCE,"properties":{**EVIDENCE["properties"],"valor":{"type":["string","null"]}}}
FIELD_NAMES=["empresa","empresa_normalizada","cnpj","orgao","numero_concorrencia_original","numero_concorrencia_normalizado","processo_sei","lote","objeto","vigencia_data_inicial","vigencia_data_final","valor_premio","numero_registro_susep","linha_digitavel_boleto"]
POLICY_LOT_SCHEMA={"type":"object","additionalProperties":False,"properties":{"numero":EVIDENCE,"valor_premio":EVIDENCE},"required":["numero","valor_premio"]}
POLICY_SCHEMA={"type":"object","additionalProperties":False,"properties":{**{name:(CNPJ_EVIDENCE if name=="cnpj" else EVIDENCE) for name in FIELD_NAMES},"lotes":{"type":"array","items":POLICY_LOT_SCHEMA},"par_coerente":{"type":"boolean"},"orgao_normalizado":{"type":["string","null"]},"tipo_empresa":{"type":["string","null"],"enum":["THI","PHAS",None]},"nome_pasta":{"type":["string","null"]},"nome_apolice":{"type":["string","null"]},"nome_boleto":{"type":["string","null"]},"confianca_geral":{"type":"number","minimum":0,"maximum":1},"campos_com_duvida":{"type":"array","items":{"type":"string"}},"observacoes":{"type":["string","null"]}},"required":FIELD_NAMES+["lotes","par_coerente","orgao_normalizado","tipo_empresa","nome_pasta","nome_apolice","nome_boleto","confianca_geral","campos_com_duvida","observacoes"]}
GROUP_SCHEMA={"type":"object","additionalProperties":False,"properties":{"lote":EVIDENCE,"lotes":{"type":"array","items":EVIDENCE},"apolice":{"type":["string","null"]},"boleto":{"type":["string","null"]}},"required":["lote","lotes","apolice","boleto"]}
ROLE_SCHEMA={"type":"object","additionalProperties":False,"properties":{"grupos":{"type":"array","items":GROUP_SCHEMA},"outros":{"type":"array","items":{"type":"string"}},"observacoes":{"type":["string","null"]}},"required":["grupos","outros","observacoes"]}
SYSTEM_PROMPT="""Você é um sistema multimodal de extração documental de apólices de seguro relacionadas a licitações brasileiras. Nesta chamada recebe as primeiras páginas de UMA apólice e o boleto completo associado. Um único par de PDFs pode cobrir vários lotes; isso continua sendo um único grupo/documento, não invente nem exija um par de PDFs por lote. Extraia somente informações efetivamente sustentadas pelos documentos. Defina par_coerente=true somente se apólice e boleto se referirem ao mesmo contrato/licitação e os lotes forem compatíveis; se houver conflito ou não for seguro, false. Compare órgão, número da concorrência e todos os identificadores explícitos de lote nos dois arquivos; registre conflitos em observacoes/campos_com_duvida.

NUNCA invente, complete dígitos, deduza dados ausentes ou transforme incerteza em certeza. Para dado ausente/ilegível retorne valor=null, fonte=NAO_IDENTIFICADO, confiança baixa e inclua o campo em campos_com_duvida. A confiança é por campo e baseada na evidência legível. Indique APOLICE, BOLETO, AMBOS ou NAO_IDENTIFICADO.

Prioridade: seguro, empresa, CNPJ da empresa/tomador, órgão, concorrência, SEI, lotes, objeto, vigência e SUSEP: apólice; linha digitável: boleto; prêmio: apólice, mencionando conflito com boleto. Preserve o nome jurídico original em empresa e transcreva o CNPJ apenas quando legível no documento. Empresa normalizada somente THI ou PHAS quando sustentada pelos documentos. Datas ISO YYYY-MM-DD; prêmio número decimal. Linha digitável transcrita exatamente, sem validação/correção/completar. Preserve número original da concorrência e produza forma normalizada substituindo separadores por hífens, sem alterar algarismos. Para cada lote explícito, preencha lotes como lista de objetos {numero:{valor,fonte,confianca},valor_premio:{valor,fonte,confianca}}. Não trunque listas longas, não junte números em texto como “1 e 2”, não deduza lotes. Se houver apenas um lote, mantenha também lote como compatibilidade; com vários lotes, lote deve ser null e a lista lotes deve conter TODOS. Se houver prêmio individual por lote, registre-o apenas na entrada correspondente e deixe valor_premio geral null; se houver um único prêmio geral, use-o no campo geral e mantenha valores individuais nulos. Se não identificável, use valor null e fonte NAO_IDENTIFICADO.

Nomes finais serão gerados pelo Python, não use sugestões da IA como caminhos."""
def role_prompt(names:list[str])->str:
    return ("Classifique semanticamente TODOS os PDFs anexados. Pode haver muitas apólices e boletos, grupos de múltiplos lotes e documentos OUTRO. Devolva exatamente cada nome de arquivo anexado uma vez, sem alterar grafia. Crie um grupo por PAR FÍSICO de apólice+boleto, não um grupo por lote. Um mesmo par pode cobrir N lotes; nesse caso atribua a lista completa em lotes (cada item {valor, fonte, confianca}) e não duplique os nomes dos PDFs. Use lote (campo legado) somente se houver exatamente um lote; para vários, lote com valor null. Agrupe pares pela correspondência semântica entre conteúdo, identificadores dos lotes (no nome, corpo, tabelas, boleto ou apólice), órgão e concorrência. NUNCA associe apenas pela ordem dos anexos nem associe documentos de contratos/lotes divergentes. Retorne apolice e boleto como nomes exatos, null se a contraparte faltar/for ambígua. Arquivos alheios vão em outros. Não descarte documentos, não trunque listas e não transforme múltiplos identificadores em string como “1 e 2”. Se houver ambiguidade, descreva em observacoes e deixe o grupo incompleto para revisão. Os nomes anexados são: "+"; ".join(names))
def policy_prompt(company_names:list[str]|None=None,expected_lot:str|None=None,expected_lots:list[str]|None=None)->str:
    references=""
    if company_names:references="\nNomes jurídicos de referência configurados: "+"; ".join(company_names)+". Servem apenas para reconhecer nomes impressos, não como prova independente."
    group=""
    if expected_lot is not None:group=f"\nA classificação anterior associou este par ao lote {expected_lot!r}. Confira os documentos: o mesmo par pode também cobrir outros lotes. Retorne todos em lotes[]; não restrinja a lista ao lote de contexto. Se houver exatamente um, use lote como compatibilidade; com vários, lote deve ser null."
    if expected_lots:group=f"\nA classificação anterior associou ESTE ÚNICO PAR aos lotes {expected_lots!r}. Confira e extraia cada lote individualmente da apólice; não replique PDFs nem reduza a lista."
    return SYSTEM_PROMPT+references+group+"\nRetorne exclusivamente JSON compatível com schema strict. Cada campo em FIELD_NAMES é {valor, fonte, confianca}; lotes é sempre uma lista estruturada. Para lote não identificável, use valor null e baixa confiança."
